version: '2'

services:
  rabbitmq:
    image: 'rabbitmq:3.8-management'
    ports:
      - '5672:5672'
      - '15672:15672'
      - '25672:25672'
      - '4369:4369'
    volumes:
      - 'rabbitmq_data:/rabbitmq'

  postgres:
    image: 'postgres:12-alpine'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=delivery
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data/

volumes:
  pg_data:
  rabbitmq_data:
    driver: local
