spring:
  datasource:
    url: jdbc:postgresql://localhost/delivery
    username: postgres
    password: postgres
    hikari:
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          max-interval: 10000
          multiplier: 2.0
          stateless: true

auth0:
  audience: https://delivery/api
  issuer: https://dev-delivery.auth0.com/

logging:
  level:
    datadog: DEBUG
    com:
      auth0: DEBUG
    org:
      springframework:
        security: DEBUG
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql: TRACE
#  file:
#    path: log

dd:
  service:
    name: "Delivery"
  integration:
    jdbc-datasource:
      enabled: true


springdoc:
  swagger-ui:
    path: '/swagger.html'

management:
  metrics:
    export:
      datadog:
        api-key: ${DD_KEY}
  endpoints:
    web:
      exposure:
        include: metrics