spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    hikari:
      maximumPoolSize: 10
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false

auth0:
  audience: https://delivery/api
  issuer: https://dev-delivery.auth0.com/

logging:
  level:
    com:
      auth0: WARN
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql: TRACE
#  file:
#    path: log



management:
  metrics:
    export:
      datadog:
        api-key: ${DD_KEY}
  endpoints:
    web:
      exposure:
        include: metrics